// Generated by CoffeeScript 1.10.0
(function() {
  var fs, iconv;

  fs = require('fs');

  iconv = require('iconv-lite');

  fs.readFile('/Users/salho/Downloads/Veroeffentlichung_3Abs3MedKFTG_2015_Q1.csv', function(err, data) {
    return console.log(iconv.decode(data, 'latin1'));
  });

}).call(this);
